/**
 * Publisher relay.
 *
 * Two different problems land here, and both are about WHERE a request comes
 * from rather than what it asks for. Some publishers answer an ordinary
 * datacenter egress normally while refusing one particular hosting
 * provider's ranges. And aggregator queries are rate-limited per egress, so
 * running them from somewhere else takes them off a shared ceiling.
 *
 * Either way this script fetches each publisher's PUBLIC surface and
 * forwards the raw payload to the configured endpoint, which parses it with
 * its own mappers.
 *
 * targets.json is GENERATED by the consuming application. Never hand-edit
 * it: the receiving end keeps its own allowlist built from the same source,
 * so an edited entry is rejected on arrival.
 *
 * No dependencies; runs on the runner's Node 20+ (global fetch).
 * Secrets: FETCHER_URL + FETCHER_SECRET (repo Actions secrets).
 */
import { readFileSync } from "node:fs";

const FETCHER_URL = process.env.FETCHER_URL;
const FETCHER_SECRET = process.env.FETCHER_SECRET;

const TARGETS = JSON.parse(
  readFileSync(new URL("./targets.json", import.meta.url), "utf8"),
);

/** How many publishers are in flight at once. Small on purpose: the run has
 * half an hour of headroom, and a burst of seventy simultaneous requests is
 * exactly the shape that gets an egress range rate-limited — the problem
 * this relay exists to solve. */
const CONCURRENCY = 6;

/** Per-request ceiling. Publishers that are slow rather than blocked used
 * to eat the Worker's whole fetch budget; here a straggler costs only its
 * own slot. */
const FETCH_TIMEOUT_MS = 20_000;

// The fetcher's guard is 2 MiB. Truncate oversized HTML (cheerio parses a
// truncated homepage fine — the top cards survive); never truncate JSON,
// and never truncate XML (a half-closed document parses to nothing).
const MAX_PAYLOAD = 1_900_000;

const BROWSER_HEADERS = {
  "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
  "Accept-Language": "el-GR,el;q=0.9,en;q=0.8",
};

const ACCEPT = {
  wpjson: "application/json, text/plain, */*",
  html: "text/html,*/*",
  rss: "application/rss+xml, application/xml;q=0.9, */*;q=0.8",
  sitemap: "application/xml, text/xml;q=0.9, */*;q=0.8",
};

async function fetchPayload(t) {
  const res = await fetch(t.url, {
    headers: {
      ...BROWSER_HEADERS,
      Accept: ACCEPT[t.kind] ?? "*/*",
      Referer: t.referer,
    },
    redirect: "follow",
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  // A single 503 from an aggregator is usually a momentary rate-limit
  // rather than a wall; one cheap retry recovers most of them.
  if (res.status === 503) {
    await new Promise((r) => setTimeout(r, 3000));
    return fetchPayload({ ...t, _retried: true });
  }
  if (!res.ok) throw new Error(`publisher HTTP ${res.status}`);
  const payload = await res.text();
  if (payload.length > MAX_PAYLOAD) {
    if (t.kind === "html") return payload.slice(0, MAX_PAYLOAD);
    throw new Error(`payload too large (${payload.length} bytes)`);
  }
  return payload;
}

/** Google News query for a publisher's own domain — the fallback surface
 * when the publisher blocks this egress too. Google crawls publishers from
 * its own infrastructure, so a 403 against us says nothing about what Google
 * has indexed. The payload is always RSS, which is why the fetcher accepts
 * an `rss` document for a source whose primary surface is a sitemap. */
function aggregatorUrl(referer) {
  const host = new URL(referer).hostname.replace(/^www\./, "");
  const q = encodeURIComponent(`site:${host}`);
  return `https://news.google.com/rss/search?q=${q}&hl=el&gl=GR&ceid=GR:el`;
}

async function relayOne(t) {
  let kind = t.kind;
  let payload;
  try {
    payload = await fetchPayload(t);
  } catch (e) {
    // Only a document-shaped source has a meaningful fallback; a wp-json or
    // homepage-scrape mapper cannot read an aggregator feed.
    if (t.kind !== "rss" && t.kind !== "sitemap") throw e;
    payload = await fetchPayload({
      ...t,
      kind: "rss",
      url: aggregatorUrl(t.referer),
    });
    kind = "rss";
  }
  const post = await fetch(`${FETCHER_URL}/ingest-external`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${FETCHER_SECRET}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ source: t.source, kind, payload }),
    signal: AbortSignal.timeout(30_000),
  });
  const bodyText = (await post.text()).trim();
  if (!post.ok) throw new Error(`fetcher HTTP ${post.status}: ${bodyText}`);
  return { bytes: payload.length, kind, viaFallback: kind !== t.kind };
}

if (!FETCHER_URL || !FETCHER_SECRET) {
  console.error("FETCHER_URL / FETCHER_SECRET not configured");
  process.exit(1);
}

let ok = 0;
let failures = 0;
const queue = [...TARGETS];

async function worker() {
  for (;;) {
    const t = queue.shift();
    if (!t) return;
    try {
      const r = await relayOne(t);
      ok++;
      console.log(
        `✓ ${t.source} (${r.kind}${r.viaFallback ? ", fallback" : ""}): relayed ${r.bytes} bytes`,
      );
    } catch (e) {
      failures++;
      console.error(`✗ ${t.source} (${t.kind}): ${e.message}`);
    }
  }
}

await Promise.all(
  Array.from({ length: Math.min(CONCURRENCY, TARGETS.length) }, worker),
);

console.log(`\n${ok} relayed · ${failures} failed · ${TARGETS.length} targets`);
// Red run only when NOTHING got through — individual publisher hiccups are
// routine at this roster size and self-heal on the next half-hour fire.
if (ok === 0) process.exit(1);
