/**
 * Publisher relay.
 *
 * Two different problems land here, and both are about WHERE a request comes
 * from rather than what it asks for. Some publishers answer an ordinary
 * datacenter egress normally while refusing one particular hosting
 * provider's ranges. And aggregator queries are rate-limited per egress, so
 * running them from somewhere else takes them off a shared ceiling.
 *
 * Either way this script fetches each publisher's PUBLIC surface and
 * forwards the raw payload to the configured endpoint, which parses it with
 * its own mappers.
 *
 * targets.json is GENERATED by the consuming application. Never hand-edit
 * it: the receiving end keeps its own allowlist built from the same source,
 * so an edited entry is rejected on arrival.
 *
 * No dependencies; runs on the runner's Node 20+ (global fetch).
 * Secrets: FETCHER_URL + FETCHER_SECRET (repo Actions secrets).
 */
import { readFileSync } from "node:fs";

const FETCHER_URL = process.env.FETCHER_URL;
const FETCHER_SECRET = process.env.FETCHER_SECRET;

const TARGETS = JSON.parse(
  readFileSync(new URL("./targets.json", import.meta.url), "utf8"),
);

/** How many publishers are in flight at once. Small on purpose: the run has
 * half an hour of headroom, and a burst of seventy simultaneous requests is
 * exactly the shape that gets an egress range rate-limited — the problem
 * this relay exists to solve. */
const CONCURRENCY = 6;

/** Per-request ceiling. Publishers that are slow rather than blocked used
 * to eat the Worker's whole fetch budget; here a straggler costs only its
 * own slot. */
const FETCH_TIMEOUT_MS = 20_000;

// The fetcher's guard is 2 MiB. Truncate oversized HTML (cheerio parses a
// truncated homepage fine — the top cards survive); never truncate JSON,
// and never truncate XML (a half-closed document parses to nothing).
const MAX_PAYLOAD = 1_900_000;

const BROWSER_HEADERS = {
  "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
  "Accept-Language": "el-GR,el;q=0.9,en;q=0.8",
};

const ACCEPT = {
  wpjson: "application/json, text/plain, */*",
  html: "text/html,*/*",
  rss: "application/rss+xml, application/xml;q=0.9, */*;q=0.8",
  sitemap: "application/xml, text/xml;q=0.9, */*;q=0.8",
};

async function fetchPayload(t) {
  const res = await fetch(t.url, {
    headers: {
      ...BROWSER_HEADERS,
      Accept: ACCEPT[t.kind] ?? "*/*",
      Referer: t.referer,
    },
    redirect: "follow",
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  // A single 503 from an aggregator is usually a momentary rate-limit
  // rather than a wall; one cheap retry recovers most of them.
  //
  // THE GUARD THIS COMMENT ALWAYS IMPLIED WAS NEVER WRITTEN. `_retried` was
  // set here and read nowhere, so a publisher that answers 503 EVERY time
  // recursed for ever: fetch, sleep 3s, fetch, sleep 3s. With CONCURRENCY 6
  // one such target holds a worker permanently, `Promise.all` never settles,
  // and the job runs to its 12-minute timeout — so ONE misbehaving publisher
  // silently stopped all 92 from relaying, not just itself.
  //
  // Measured 2026-08-01: every run for weeks took 0.4-0.6 min; the two runs
  // after a permanently-503ing origin was added took 12.3 min and were
  // cancelled. The origin was the trigger, this was the fault.
  if (res.status === 503 && !t._retried) {
    await new Promise((r) => setTimeout(r, 3000));
    return fetchPayload({ ...t, _retried: true });
  }
  if (!res.ok) {
    // Ο ΚΩΔΙΚΟΣ ΤΑΞΙΔΕΥΕΙ ΜΕ ΤΟ ΣΦΑΛΜΑ. Ήταν μόνο μέσα στο κείμενο του
    // μηνύματος, οπότε ο καλών θα έπρεπε να το ξαναδιαβάσει με regex — και
    // δεν το έκανε: το πετούσε ολόκληρο.
    const err = new Error(`publisher HTTP ${res.status}`);
    err.status = res.status;
    err.snippet = (await res.text().catch(() => ""))
      .slice(0, 160)
      .replace(/\s+/g, " ")
      .trim();
    throw err;
  }
  const payload = await res.text();
  if (payload.length > MAX_PAYLOAD) {
    if (t.kind === "html") return payload.slice(0, MAX_PAYLOAD);
    throw new Error(`payload too large (${payload.length} bytes)`);
  }
  return payload;
}

/** Google News query for a publisher's own domain — the fallback surface
 * when the publisher blocks this egress too. Google crawls publishers from
 * its own infrastructure, so a 403 against us says nothing about what Google
 * has indexed. The payload is always RSS, which is why the fetcher accepts
 * an `rss` document for a source whose primary surface is a sitemap. */
function aggregatorUrl(referer) {
  const host = new URL(referer).hostname.replace(/^www\./, "");
  const q = encodeURIComponent(`site:${host}`);
  return `https://news.google.com/rss/search?q=${q}&hl=el&gl=GR&ceid=GR:el`;
}

/**
 * ⛔⛔ Ο ΑΝΑΜΕΤΑΔΟΤΗΣ ΔΕΝ ΑΠΟΦΑΣΙΖΕΙ ΠΙΑ — ΒΗΜΑ 10, 2026-08-17.
 *
 * Ρωτά τον Worker τι να κάνει με μια άρνηση εκδότη. Ο Worker έχει τα στοιχεία
 * που λείπουν εδώ: τι βλέπει το ΔΙΚΟ ΤΟΥ colo (μετακινήθηκε τρεις φορές σε μία
 * μέρα, AMS → IAD → SIN), σε τι κατάσταση είναι η πηγή, και ότι μια διεύθυνση
 * Google είναι αδιαφανές blob που ΔΕΝ επιδιορθώνεται αργότερα.
 *
 * ⚠ ΑΠΟΤΥΧΙΑ ΤΗΣ ΕΡΩΤΗΣΗΣ ΔΕΝ ΣΤΑΜΑΤΑ ΤΗΝ ΥΛΗ. Αν ο Worker δεν απαντήσει,
 * κρατιέται η παλιά συμπεριφορά (συλλέκτης): το να σιωπήσει μια πηγή επειδή
 * έπεσε μια βοηθητική κλήση είναι χειρότερο από μια ΔΗΛΩΜΕΝΗ υποβάθμιση.
 */
async function askRouting(source, refusalStatus, refusalMessage) {
  try {
    const res = await fetch(`${FETCHER_URL}/relay-refusal`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${FETCHER_SECRET}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ source, refusalStatus, refusalMessage }),
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok)
      return { then: "aggregator", reason: `ο Worker απάντησε ${res.status}` };
    return await res.json();
  } catch (e) {
    return { then: "aggregator", reason: `η ερώτηση δρομολόγησης απέτυχε: ${e.message}` };
  }
}

async function relayOne(t) {
  let kind = t.kind;
  // ⚠ THIS FLAG USED TO BE DERIVED AND WAS WRONG FOR MOST OF THE ROSTER.
  // It read `kind !== t.kind`, which only differs when a SITEMAP target falls
  // back to the aggregator's RSS. When an `rss` target falls back, the
  // aggregator payload is ALSO `rss`, so the comparison returned false while
  // the publisher had in fact been replaced by Google News. Measured
  // 2026-08-16: targets.json holds 75 rss of 88, so the derived flag was blind
  // to 85% of the roster — precisely the cohort the flag exists to expose.
  // Set it where the substitution happens, and never infer it downstream.
  let viaFallback = false;
  let payload;
  let refusalStatus = null;
  let refusalMessage = null;
  try {
    payload = await fetchPayload(t);
  } catch (e) {
    // Only a document-shaped source has a meaningful fallback; a wp-json or
    // homepage-scrape mapper cannot read an aggregator feed.
    if (t.kind !== "rss" && t.kind !== "sitemap") throw e;
    refusalStatus = typeof e.status === "number" ? e.status : null;
    refusalMessage = e.snippet || e.message || null;
    // Η ΑΠΟΦΑΣΗ ΕΙΝΑΙ ΤΟΥ WORKER. Δες askRouting παραπάνω.
    const routing = await askRouting(t.source, refusalStatus, refusalMessage);
    if (routing.then !== "aggregator") {
      throw new Error(
        `${e.message} → ο Worker είπε ${routing.then}: ${routing.reason}`,
      );
    }
    payload = await fetchPayload({
      ...t,
      kind: "rss",
      url: aggregatorUrl(t.referer),
    });
    kind = "rss";
    viaFallback = true;
  }
  const post = await fetch(`${FETCHER_URL}/ingest-external`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${FETCHER_SECRET}`,
      "Content-Type": "application/json",
    },
    // `viaFallback` MUST travel with the payload. Until 2026-08-16 it was
    // computed here, printed to the run log, and dropped — so the consumer
    // wrote every aggregator-substituted payload as an ordinary success and
    // stamped a freshness date from Google News. Zero failures, zero alerts,
    // a green board for days over two nearly-silent publishers.
    body: JSON.stringify({ source: t.source, kind, payload, viaFallback, refusalStatus, refusalMessage }),
    signal: AbortSignal.timeout(30_000),
  });
  const bodyText = (await post.text()).trim();
  if (!post.ok) throw new Error(`fetcher HTTP ${post.status}: ${bodyText}`);
  return { bytes: payload.length, kind, viaFallback };
}

if (!FETCHER_URL || !FETCHER_SECRET) {
  console.error("FETCHER_URL / FETCHER_SECRET not configured");
  process.exit(1);
}

let ok = 0;
let failures = 0;
// Counted separately from `ok` on purpose. A run where every publisher was
// substituted by the aggregator is not a healthy run, and until this line
// existed the summary reported it as one.
const fallbacks = [];
const queue = [...TARGETS];

async function worker() {
  for (;;) {
    const t = queue.shift();
    if (!t) return;
    try {
      const r = await relayOne(t);
      ok++;
      if (r.viaFallback) fallbacks.push(t.source);
      console.log(
        `✓ ${t.source} (${r.kind}${r.viaFallback ? ", fallback" : ""}): relayed ${r.bytes} bytes`,
      );
    } catch (e) {
      failures++;
      console.error(`✗ ${t.source} (${t.kind}): ${e.message}`);
    }
  }
}

await Promise.all(
  Array.from({ length: Math.min(CONCURRENCY, TARGETS.length) }, worker),
);

console.log(
  `\n${ok} relayed · ${fallbacks.length} via aggregator · ${failures} failed · ${TARGETS.length} targets`,
);
if (fallbacks.length > 0) {
  console.log(`  aggregator-substituted: ${fallbacks.join(", ")}`);
}
// Red run only when NOTHING got through — individual publisher hiccups are
// routine at this roster size and self-heal on the next half-hour fire.
if (ok === 0) process.exit(1);
