/**
 * Publisher relay.
 *
 * Two different problems land here, and both are about WHERE a request comes
 * from rather than what it asks for. Some publishers answer an ordinary
 * datacenter egress normally while refusing one particular hosting
 * provider's ranges. And aggregator queries are rate-limited per egress, so
 * running them from somewhere else takes them off a shared ceiling.
 *
 * Either way this script fetches each publisher's PUBLIC surface and
 * forwards the raw payload to the configured endpoint, which parses it with
 * its own mappers.
 *
 * targets.json is GENERATED by the consuming application. Never hand-edit
 * it: the receiving end keeps its own allowlist built from the same source,
 * so an edited entry is rejected on arrival.
 *
 * No dependencies; runs on the runner's Node 20+ (global fetch).
 * Secrets: FETCHER_URL + FETCHER_SECRET (repo Actions secrets).
 */
import { readFileSync } from "node:fs";

const FETCHER_URL = process.env.FETCHER_URL;
const FETCHER_SECRET = process.env.FETCHER_SECRET;

const TARGETS = JSON.parse(
  readFileSync(new URL("./targets.json", import.meta.url), "utf8"),
);

/** How many publishers are in flight at once. Small on purpose: the run has
 * half an hour of headroom, and a burst of seventy simultaneous requests is
 * exactly the shape that gets an egress range rate-limited — the problem
 * this relay exists to solve. */
const CONCURRENCY = 6;

/** Per-request ceiling. Publishers that are slow rather than blocked used
 * to eat the Worker's whole fetch budget; here a straggler costs only its
 * own slot. */
const FETCH_TIMEOUT_MS = 20_000;

// The fetcher's guard is 2 MiB. Truncate oversized HTML (cheerio parses a
// truncated homepage fine — the top cards survive); never truncate JSON,
// and never truncate XML (a half-closed document parses to nothing).
import {
  resolveAggregatorLinks,
  resolveGoogleNewsUrl,
  RESOLVE_CONCURRENCY,
} from "./resolve-google.mjs";
import {
  dayOf,
  isGoogleNewsPrimary,
  loadMemo,
  markRefused,
  newRunContext,
  resolvePrimaryLinks,
  saveMemo,
} from "./link-memo.mjs";

const MAX_PAYLOAD = 1_900_000;

const BROWSER_HEADERS = {
  "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
  "Accept-Language": "el-GR,el;q=0.9,en;q=0.8",
};

/** ⛔ ΤΟ ΤΑΒΑΝΙ ΤΟΥ 3236: αναλύσεις ανά run για τους κύριους στόχους Google
 * News, ΟΛΟΙ μαζί. Κάθε ανάλυση είναι το πολύ δύο αιτήματα (σελίδα και
 * batchexecute), άρα 100 σημαίνει ≤200 αιτήματα. Μετρημένο 5/10: ≈863 νέα άρθρα
 * την ημέρα στους 23, ≈28 ανά run· το 100 χωρά τις αιχμές της ημέρας. Η εφεδρική
 * ΔΕΝ μετρά εδώ: έχει το δικό της `RESOLVE_CAP` ανά στόχο, όπως πριν.
 * Τιμή που δεν διαβάζεται ως αριθμός ≥ 0 δίνει 0, όχι άπειρο. */
const capRaw = Number(process.env.GN_PRIMARY_RESOLVE_CAP ?? 100);
const GN_PRIMARY_RESOLVE_CAP =
  Number.isFinite(capRaw) && capRaw >= 0 ? Math.floor(capRaw) : 0;
const GN_LINKS_FILE = process.env.GN_LINKS_FILE ?? "gn-links.json";

const today = dayOf(Date.now());
const { memo, found: memoFound } = loadMemo(GN_LINKS_FILE);
const memoLoaded = Object.values(memo.t).reduce((s, e) => s + Object.keys(e).length, 0);
const gn = newRunContext(GN_PRIMARY_RESOLVE_CAP);

const ACCEPT = {
  wpjson: "application/json, text/plain, */*",
  html: "text/html,*/*",
  rss: "application/rss+xml, application/xml;q=0.9, */*;q=0.8",
  sitemap: "application/xml, text/xml;q=0.9, */*;q=0.8",
};

async function fetchPayload(t) {
  const res = await fetch(t.url, {
    headers: {
      ...BROWSER_HEADERS,
      Accept: ACCEPT[t.kind] ?? "*/*",
      Referer: t.referer,
    },
    redirect: "follow",
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  // A single 503 from an aggregator is usually a momentary rate-limit
  // rather than a wall; one cheap retry recovers most of them.
  //
  // THE GUARD THIS COMMENT ALWAYS IMPLIED WAS NEVER WRITTEN. `_retried` was
  // set here and read nowhere, so a publisher that answers 503 EVERY time
  // recursed for ever: fetch, sleep 3s, fetch, sleep 3s. With CONCURRENCY 6
  // one such target holds a worker permanently, `Promise.all` never settles,
  // and the job runs to its 12-minute timeout — so ONE misbehaving publisher
  // silently stopped all 92 from relaying, not just itself.
  //
  // Measured 2026-08-01: every run for weeks took 0.4-0.6 min; the two runs
  // after a permanently-503ing origin was added took 12.3 min and were
  // cancelled. The origin was the trigger, this was the fault.
  if (res.status === 503 && !t._retried) {
    await new Promise((r) => setTimeout(r, 3000));
    return fetchPayload({ ...t, _retried: true });
  }
  if (!res.ok) {
    // Ο ΚΩΔΙΚΟΣ ΤΑΞΙΔΕΥΕΙ ΜΕ ΤΟ ΣΦΑΛΜΑ. Ήταν μόνο μέσα στο κείμενο του
    // μηνύματος, οπότε ο καλών θα έπρεπε να το ξαναδιαβάσει με regex — και
    // δεν το έκανε: το πετούσε ολόκληρο.
    const err = new Error(`publisher HTTP ${res.status}`);
    err.status = res.status;
    err.snippet = (await res.text().catch(() => ""))
      .slice(0, 160)
      .replace(/\s+/g, " ")
      .trim();
    throw err;
  }
  const payload = await res.text();
  if (payload.length > MAX_PAYLOAD) {
    if (t.kind === "html") return payload.slice(0, MAX_PAYLOAD);
    throw new Error(`payload too large (${payload.length} bytes)`);
  }
  return payload;
}

/** Google News query for a publisher's own domain — the fallback surface
 * when the publisher blocks this egress too. Google crawls publishers from
 * its own infrastructure, so a 403 against us says nothing about what Google
 * has indexed. The payload is always RSS, which is why the fetcher accepts
 * an `rss` document for a source whose primary surface is a sitemap. */
function aggregatorUrl(referer) {
  // Domain AND path: BasketNews.gr moved to basketnews.com/gr/ (2026-10-05),
  // and basketnews.com carries other editions too. No other referer has a path.
  const u = new URL(referer);
  const host = u.hostname.replace(/^www\./, "") + u.pathname.replace(/\/+$/, "");
  // when:1d: without it Google answers 100 items ranked by RELEVANCE, mostly
  // old, and the newest articles are not among them (measured 2026-10-04 on
  // 23 fallback sources: 456 -> 783 articles of the last 48h in the answer).
  // The consuming application builds the same query in one helper
  // (lib/google-news-query.ts); a change there needs this line too.
  const q = encodeURIComponent(`site:${host} when:1d`);
  return `https://news.google.com/rss/search?q=${q}&hl=el&gl=GR&ceid=GR:el`;
}

/**
 * ⛔⛔ Ο ΑΝΑΜΕΤΑΔΟΤΗΣ ΔΕΝ ΑΠΟΦΑΣΙΖΕΙ ΠΙΑ — ΒΗΜΑ 10, 2026-08-17.
 *
 * Ρωτά τον Worker τι να κάνει με μια άρνηση εκδότη. Ο Worker έχει τα στοιχεία
 * που λείπουν εδώ: τι βλέπει το ΔΙΚΟ ΤΟΥ colo (μετακινήθηκε τρεις φορές σε μία
 * μέρα, AMS → IAD → SIN), σε τι κατάσταση είναι η πηγή, και ότι μια διεύθυνση
 * Google είναι αδιαφανές blob που ΔΕΝ επιδιορθώνεται αργότερα.
 *
 * ⚠ ΑΠΟΤΥΧΙΑ ΤΗΣ ΕΡΩΤΗΣΗΣ ΔΕΝ ΣΤΑΜΑΤΑ ΤΗΝ ΥΛΗ. Αν ο Worker δεν απαντήσει,
 * κρατιέται η παλιά συμπεριφορά (συλλέκτης): το να σιωπήσει μια πηγή επειδή
 * έπεσε μια βοηθητική κλήση είναι χειρότερο από μια ΔΗΛΩΜΕΝΗ υποβάθμιση.
 */
async function askRouting(source, refusalStatus, refusalMessage) {
  try {
    const res = await fetch(`${FETCHER_URL}/relay-refusal`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${FETCHER_SECRET}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ source, refusalStatus, refusalMessage }),
      signal: AbortSignal.timeout(10_000),
    });
    if (!res.ok)
      return { then: "aggregator", reason: `ο Worker απάντησε ${res.status}` };
    return await res.json();
  } catch (e) {
    return { then: "aggregator", reason: `η ερώτηση δρομολόγησης απέτυχε: ${e.message}` };
  }
}

/** ⛔ 3266: ποιοι σύνδεσμοι Google News υπάρχουν ήδη στη D1. Πετά σφάλμα αν ο
 * Worker δεν απαντήσει· τότε δεν αναλύεται τίποτα (δες link-memo.mjs). */
async function knownLinks(links) {
  const res = await fetch(`${FETCHER_URL}/known-urls`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${FETCHER_SECRET}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ urls: links }),
    signal: AbortSignal.timeout(10_000),
  });
  if (!res.ok) throw new Error(`known-urls HTTP ${res.status}`);
  const j = await res.json();
  if (!Array.isArray(j?.known)) throw new Error("known-urls: άκυρη απάντηση");
  return new Set(j.known);
}


/** Google News answers by relevance, up to 100 items, inside whatever window
 * it is given. A small publisher asked for one day answers an EMPTY channel on
 * a quiet weekend, which the Worker counts as relay_no_items (Agrotypos and
 * Axianews, email of 2026-10-04 19:36Z). So the week (`wideUrl`) is asked
 * first; a full answer means the week hides the newest items, and the day
 * query (`url`) is asked instead. The Worker keeps the 25 newest either way.
 * The consuming application builds both URLs in lib/google-news-query.ts,
 * where GOOGLE_NEWS_FULL_ANSWER must equal GN_FULL_ANSWER here. */
const GN_FULL_ANSWER = 95;

async function fetchPrimary(t) {
  if (!t.wideUrl) return fetchPayload(t);
  let wide;
  try {
    wide = await fetchPayload({ ...t, url: t.wideUrl });
  } catch {
    return fetchPayload(t);
  }
  const items = (wide.match(/<item>/g) || []).length;
  return items >= GN_FULL_ANSWER ? fetchPayload(t) : wide;
}

async function relayOne(t) {
  let kind = t.kind;
  // ⚠ THIS FLAG USED TO BE DERIVED AND WAS WRONG FOR MOST OF THE ROSTER.
  // It read `kind !== t.kind`, which only differs when a SITEMAP target falls
  // back to the aggregator's RSS. When an `rss` target falls back, the
  // aggregator payload is ALSO `rss`, so the comparison returned false while
  // the publisher had in fact been replaced by Google News. Measured
  // 2026-08-16: targets.json holds 75 rss of 88, so the derived flag was blind
  // to 85% of the roster — precisely the cohort the flag exists to expose.
  // Set it where the substitution happens, and never infer it downstream.
  let viaFallback = false;
  let payload;
  let refusalStatus = null;
  let refusalMessage = null;
  let resolvedNote = "";
  try {
    payload = await fetchPrimary(t);
  } catch (e) {
    // Only a document-shaped source has a meaningful fallback; a wp-json or
    // homepage-scrape mapper cannot read an aggregator feed.
    if (t.kind !== "rss" && t.kind !== "sitemap") throw e;
    refusalStatus = typeof e.status === "number" ? e.status : null;
    refusalMessage = e.snippet || e.message || null;
    // Το Google αρνήθηκε το ΙΔΙΟ το ερώτημα ενός κύριου στόχου: στάση και εδώ.
    if (isGoogleNewsPrimary(t) && (refusalStatus === 429 || refusalStatus === 503))
      markRefused(gn);
    // Η ΑΠΟΦΑΣΗ ΕΙΝΑΙ ΤΟΥ WORKER. Δες askRouting παραπάνω.
    const routing = await askRouting(t.source, refusalStatus, refusalMessage);
    if (routing.then !== "aggregator") {
      throw new Error(
        `${e.message} → ο Worker είπε ${routing.then}: ${routing.reason}`,
      );
    }
    payload = await fetchPayload({
      ...t,
      kind: "rss",
      url: aggregatorUrl(t.referer),
    });
    kind = "rss";
    viaFallback = true;
    // ⛔ Η ΑΝΑΛΥΣΗ ΓΙΝΕΤΑΙ ΕΔΩ, ΠΡΙΝ ΦΥΓΕΙ ΤΟ ΦΟΡΤΙΟ. Απόφαση του χειριστή
    // 2026-08-18: «βαλε αναλυση διευθυνσης, οχι απορριψη».
    // Ένας κύριος στόχος Google News περνά ΠΑΝΤΑ από τη μνήμη, και στην
    // εφεδρική: αλλιώς ό,τι κράτησε τον σύνδεσμο του Google θα αναλυόταν εδώ
    // και θα έμπαινε δεύτερη φορά.
    if (!isGoogleNewsPrimary(t)) {
      try {
        const r = await resolveAggregatorLinks(payload, BROWSER_HEADERS, () =>
          markRefused(gn),
        );
        payload = r.xml;
        // ⚠ ΛΕΓΕΤΑΙ ΔΥΝΑΤΑ, ΚΑΙ ΤΟ ΝΟΥΜΕΡΟ ΕΙΝΑΙ ΚΛΑΣΜΑ. Μια σιωπηλή πτώση στο
        // 0/25 σημαίνει ότι το Google άλλαξε σελίδα, και είναι η μόνη ένδειξη
        // που θα υπάρξει — δεν σπάει τίποτα, απλώς σταματά να διορθώνει.
        resolvedNote =
          `, διευθύνσεις ${r.resolved}/${r.total}` +
          (r.dropped > 0 ? ` (+${r.dropped} πάνω από την οροφή, ΑΜΕΤΡΗΤΕΣ)` : "") +
          (r.refused > 0 ? `, άρνηση Google ×${r.refused}` : "");
      } catch {
        resolvedNote = ", ανάλυση ΑΠΕΤΥΧΕ";
      }
    }
  }
  if (isGoogleNewsPrimary(t)) {
    // ⛔ 3236: διεύθυνση εκδότη για τα ΝΕΑ άρθρα, με ταβάνι και στάση στην
    // άρνηση. Δες link-memo.mjs για το γιατί χρειάζεται μνήμη. Αν κάτι εδώ
    // σπάσει, το φορτίο φεύγει αυτούσιο: ποτέ δεν χάνεται κύκλος ύλης.
    try {
      const r = await resolvePrimaryLinks({
        source: t.source,
        xml: payload,
        memo,
        ctx: gn,
        today,
        resolve: (link) => resolveGoogleNewsUrl(link, BROWSER_HEADERS),
        known: knownLinks,
        concurrency: RESOLVE_CONCURRENCY,
      });
      payload = r.xml;
      const why = [
        r.failures > 0 ? `${r.failures} αποτυχία` : "",
        r.refused > 0 ? `${r.refused} άρνηση` : "",
        r.notTried > 0 ? `${r.notTried} ${gn.refused ? "μετά τη στάση" : "πάνω από το ταβάνι"}` : "",
      ].filter(Boolean);
      resolvedNote = r.checkFailed
        ? ", έλεγχος D1 ΑΠΕΤΥΧΕ: καμία ανάλυση, όλα όπως ήρθαν"
        : `, διευθύνσεις ${r.resolved}/${r.fresh} νέες` +
          (why.length ? ` (μένουν Google: ${why.join(", ")})` : "") +
          (r.stored > 0 ? `, ${r.stored} ήδη στη D1` : "") +
          (r.reused > 0 ? `, ${r.reused} από τη μνήμη` : "") +
          (r.cold ? ", πρώτη φορά στη μνήμη" : "");
    } catch (e) {
      resolvedNote = `, ανάλυση ΑΠΕΤΥΧΕ (${e.message})`;
    }
  }
  const post = await fetch(`${FETCHER_URL}/ingest-external`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${FETCHER_SECRET}`,
      "Content-Type": "application/json",
    },
    // `viaFallback` MUST travel with the payload. Until 2026-08-16 it was
    // computed here, printed to the run log, and dropped — so the consumer
    // wrote every aggregator-substituted payload as an ordinary success and
    // stamped a freshness date from Google News. Zero failures, zero alerts,
    // a green board for days over two nearly-silent publishers.
    body: JSON.stringify({ source: t.source, kind, payload, viaFallback, refusalStatus, refusalMessage }),
    signal: AbortSignal.timeout(30_000),
  });
  const bodyText = (await post.text()).trim();
  if (!post.ok) throw new Error(`fetcher HTTP ${post.status}: ${bodyText}`);
  return { bytes: payload.length, kind, viaFallback, resolvedNote };
}

if (!FETCHER_URL || !FETCHER_SECRET) {
  console.error("FETCHER_URL / FETCHER_SECRET not configured");
  process.exit(1);
}

let ok = 0;
let failures = 0;
// Counted separately from `ok` on purpose. A run where every publisher was
// substituted by the aggregator is not a healthy run, and until this line
// existed the summary reported it as one.
const fallbacks = [];
const queue = [...TARGETS];

async function worker() {
  for (;;) {
    const t = queue.shift();
    if (!t) return;
    try {
      const r = await relayOne(t);
      ok++;
      if (r.viaFallback) fallbacks.push(t.source);
      console.log(
        `✓ ${t.source} (${r.kind}${r.viaFallback ? ", fallback" : ""}${r.resolvedNote ?? ""}): relayed ${r.bytes} bytes`,
      );
    } catch (e) {
      failures++;
      console.error(`✗ ${t.source} (${t.kind}): ${e.message}`);
    }
  }
}

await Promise.all(
  Array.from({ length: Math.min(CONCURRENCY, TARGETS.length) }, worker),
);

console.log(
  `\n${ok} relayed · ${fallbacks.length} via aggregator · ${failures} failed · ${TARGETS.length} targets`,
);
if (fallbacks.length > 0) {
  console.log(`  aggregator-substituted: ${fallbacks.join(", ")}`);
}

// Η μνήμη γράφεται ΠΡΙΝ από το κόκκινο έξοδο: λέει με ποια διεύθυνση έφυγε κάθε
// άρθρο, και αυτό ισχύει είτε το run πέτυχε είτε όχι.
let memoNote;
try {
  const s = saveMemo(GN_LINKS_FILE, memo, today);
  memoNote = `γράφτηκαν ${s.kept} σε ${Object.keys(memo.t).length} στόχους (σβήστηκαν ${s.pruned})`;
} catch (e) {
  memoNote = `ΔΕΝ ΓΡΑΦΤΗΚΕ: ${e.message}`;
}
console.log(
  `Google News κύριοι στόχοι: νέες ${gn.fresh} · αναλύθηκαν ${gn.resolved} · ` +
    `μένουν Google ${gn.fresh - gn.resolved} (ταβάνι ${gn.keptCap}, άρνηση ${gn.keptRefused}, αποτυχία ${gn.failures}) · ` +
    `ήδη στη D1 ${gn.stored}` +
    (gn.checkFailed > 0 ? ` · έλεγχος D1 ΑΠΕΤΥΧΕ σε ${gn.checkFailed} στόχους` : "") +
    ` · αναλύσεις ${gn.calls}/${GN_PRIMARY_RESOLVE_CAP} (≤${2 * gn.calls} αιτήματα) · ` +
    `στάση 429/503: ${gn.refused ? `ΝΑΙ ${gn.refusedAt}Z` : "όχι"}`,
);
console.log(
  `μνήμη συνδέσμων: ${memoFound ? `φορτώθηκαν ${memoLoaded}` : "ΔΕΝ ΒΡΕΘΗΚΕ (κρίνει η D1)"} · ${memoNote}`,
);
// Red run only when NOTHING got through — individual publisher hiccups are
// routine at this roster size and self-heal on the next half-hour fire.
if (ok === 0) process.exit(1);
